name: Continuous Integration

on: push

jobs:
  build-and-push:
    name: Build and test library
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - run: docker --help
      # - uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: ceridan/readify-knock-knock
      #     tag_with_ref: true
