name: Continuous Integration

on: push

jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest

    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') && !contains(github.event.commits[0].message, '[ci ckip]') }}

    steps:
      - uses: actions/checkout@master

      - name: Docker build and push to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ceridan/readify-knock-knock
          tag_with_ref: true

  # deploy-azure:
  #   name: Deploy to Azure
  #   runs-on: ubuntu-latest

  #   needs: build-and-push

  #   if: ${{ github.ref == 'refs/heads/master' }}

  #   steps:
  #     - name: Login via Azure CLI
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Deploy to Azure Web Apps Linux Container
  #       uses: azure/webapps-container-deploy@v1
  #       with:
  #         app-name: readify-knock-knock-api
  #         images: ceridan/readify-knock-knock:latest

  #     - name: Azure logout
  #       run: |
  #         az logout
